apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: geek-cookbook-premix
  pass_credentials_all: false
  password: ""
  url: https://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@raw.githubusercontent.com/funkypenguin/geek-cookbook-premix/helm-charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: longhorn
  pass_credentials_all: false
  password: ""
  url: https://charts.longhorn.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: nextcloud
  pass_credentials_all: false
  password: ""
  url: https://nextcloud.github.io/helm/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: traefik
  pass_credentials_all: false
  password: ""
  url: https://helm.traefik.io/traefik
  username: ""
